FROM node:22-slim

RUN apt-get update -y && apt-get install -y openssl && apt-get install -y postgresql-client

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma
COPY setup/.docker.env .env

COPY . .

RUN npm ci

RUN npx prisma generate
RUN npm run proto:generate

RUN npm run build

EXPOSE 50051

CMD ["node", "build/app.js"]
